-- TOP 10 PRODUTOS COM MAIOR UNITIPRICE,WEIGHT,SIZE
SELECT TOP(10)* FROM DimProduct 
ORDER BY UnitPrice DESC, Weight DESC, Size DESC

SELECT TOP (10) * FROM DimProduct
ORDER BY UnitPrice DESC, WEIGHT DESC, AvailableForSaleDate ASC
